ALTER TABLE "weapons" ADD COLUMN "zorder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "gadgets" ADD COLUMN "zorder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "grenades" ADD COLUMN "zorder" INTEGER NOT NULL DEFAULT 0;
